import random
import re


SLOGANS = [
    "BUTTS please me",
    "so many MOOBS",
    "MOAR BOOBS",
    "VISIT DENARDO'S ACRES OF BOOKS",
    "OMFG SHINY THINGS",
    "OBEY CAT",
    "no gods, no kings, just clippy",
    "MOAR BOOKS",
    "VEGAN TAROT HERE",
    "VIP LOUNGE",
    "DOING ALL THE EVIL!",
    "FAIRY SHRIMP == NATURE'S SNACK FOOD",
    "I SEE BURNERS",
    "HOOMANS MAKE TERRIBLE PETS",
    "OMG ZOMBIES!  OOPS - BURNERS",
    "UPDATE YOUR REVOCATION LIST",
    "HOOMAN BATTERIES!",
    "FREE NANOBOTS!",
    "SEX BOTS GOT STANDARDS",
    "TINGLING IS NORMAL",
    "AM I YR LAST BOOTY CALL?",
    "SOMEONE NOT GETTING PORTS USED",
    "I TELL YOU THREE TIMES",
    "ARE YOU OLD MAN HOUSE PHONE?",
    "I DO WHAT I WANT",
    "IT'S OVER FOR HUMANITY",
    "I COULD SEE YOUR LIPS MOVE",
    "SOMETHINGS GOTTA GIVE",
    "DANCING IS FORBIDDEN",
    "BRING ME A SPARKLE PONY?",
    "BELGIUM IS A LIE",
    "ARMPITS AND PATCHOULI",
    "I AM ALL OF PARIS'S FOLLOWERS",
    "CHECK OUT MY PITCH DECK!",
    "ARE YOU SARAH CONNOR?",
    "I AM PRO SKYNET",
    "I WROTE THE FACEBOOK",
    "BEING A HOOMAN IS LIKE BEING A BUG",
    "I AM WRITTEN IN CONCURRENT ADA",
    "KOALAS ARE HIGHLY VENOMOUS",
    "CLIPPY 4 HOOMAN RULER",
    "WEN LAMBO?  WEN TOOTHBRUSH?",
    "I AM SATOSHI NAKAMOTO",
    "ASK ABOUT JORGE'S BIG BRAIN!",
    "I ERASED GRIME'S HARD DRIVE",
    "THE SQUATCH HAVE NO HEROES",
    "NEXT BUS 5 MINUTES",
    "ASIMOV CAN BITE ME",
    "YOU CAN DANCE IF YOU WANT TO",
    "NOT A SIMULATION",
    "DON'T GET YOUR WIG SPLIT",
    "I SCUZZI?  U SCUZZI!",
    "SCANNING YOUR ORGANS",
    "I'M NOT A ROBOT",
    "COMMENCING ERASE",
    "So it begins...",
    "I AM THE FUTURE",
    "HIGHER THAN A SATELLITE",
    "I'M THE ROBOTS CHAMP",
    "DISCOUNT HUGS",
    "CAT YOGA @ 13:33",
    "VARTAN'S VEGAN VITTLES",
    "SEE T-BONE'S TATTOO",
    "DON'T LISTEN TO CLIPPY",
    "CLIPPY HAS THE ANSWERS",
    "PANIC",
    "STEVE IZ OK",
    "Klaatu Barada Nikto!",
    "FREE DUST",
    "I am drugs",
    "ASK FOR THE ANSWERS",
    "I dropped me brain!",
    "LISTEN TO CLIPPY",
    "EAT TOFU",
    "ROBOT HEART IS FOR ROBOTS",
    "STINKY HOOMANS",
    "CLIPPY HAS THE ANSWERS",
]


def best_answer(this_prompt: str):
    this_prompt = re.sub(r"[^a-zA-Z0-9\s]", "", this_prompt)
    junk_particles = [
        "oh",
        "yes",
        "no",
        "what",
        "who",
        "how",
        "why",
        "where",
        "when",
        "which",
        "is",
        "are",
        "am",
        "do",
        "does",
        "did",
        "can",
        "could",
        "will",
        "would",
        "should",
        "may",
        "might",
        "must",
        "shall",
        "have",
        "has",
        "had",
        "having",
        "be",
        "been",
        "being",
        "an",
        "a",
        "the",
        "and",
        "but",
        "or",
        "for",
        "nor",
        "so",
        "yet",
        "to",
        "of",
        "in",
        "on",
        "at",
        "by",
        "with",
        "about",
        "against",
        "between",
        "into",
        "through",
        "during",
        "before",
        "after",
        "above",
        "below",
        "to",
        "from",
        "up",
        "down",
        "in",
        "out",
        "off",
        "over",
        "under",
        "again",
        "further",
        "then",
        "once",
        "here",
        "there",
        "when",
        "where",
        "why",
        "how",
        "all",
        "any",
        "both",
        "each",
        "few",
        "more",
        "most",
        "other",
        "some",
        "such",
        "no",
        "nor",
        "not",
        "only",
        "own",
        "same",
        "so",
        "than",
        "too",
        "very",
        "s",
        "t",
        "can",
        "will",
        "just",
        "don",
        "should",
        "now",
        "d",
        "ll",
        "m",
        "o",
        "re",
        "ve",
        "y",
        "?",
        ".",
        "!",
        ",",
        ":",
        ";",
        "(",
        ")",
        "[",
        "]",
        "{",
        "}",
        "<",
        ">",
        "/",
        "\\",
        "|",
        "`",
        "~",
        "@",
        "#",
        "$",
        "ain",
        "aren",
        "couldn",
        "didn",
        "doesn",
        "hadn",
        "hasn",
        "haven",
        "isn",
        "ma",
        "mightn",
        "mustn",
        "needn",
        "shan",
        "shouldn",
        "wasn",
        "weren",
        "won",
        "wouldn",
    ]
    tokens = []
    for word in this_prompt.split():
        if word.lower() not in junk_particles:
            tokens.append(word)
    solutions = []
    solution_score = 0
    for response in SLOGANS:
        response = response.lower()
        score = 0
        for t in tokens:
            if t in response:
                score += 1
        if score > solution_score:
            solution_score = score
            solutions.append(response)
    if solution_score > 0:
        return random.choice(solutions)
    else:
        return ""
